require("dotenv").config({ silent: true });

const {
    NODE_ENV,
    BASE_URL,
    CORS_URL,
    WEBSITE_URL,
    APP_URL,
    TIMEZONE,
    PORT,
    PGUSER,
    PGHOST,
    PGPORT,
    PGDATABASE,
    PGPASSWORD,
    DEFAULT_API_KEY,
    PASSWORD_SALT_KEY,
    SENDGRID_API_KEY,
    AWS_REGION,
    AWS_KEY_ID,
    AWS_SECRET_KEY_ACCESS,
    AWS_BUCKET,
    DEFAULT_ADMIN_EMAIL,
    EMAIL_IMAGE_BASE_URL,
    FROM_EMAIL,
    FROM_EMAIL_DISPLAY_NAME,
    GOOGLE_CLIENT_ID,
    ENCRYPTION_KEY,
} = process.env;

module.exports = {
    environment: NODE_ENV || "production",
    baseUrl: BASE_URL || "",
    corsUrl: CORS_URL ? CORS_URL.split(",") : "",
    websiteBaseUrl: WEBSITE_URL || "https://vtronicsautomation.com/",
    defaultTimeZone: TIMEZONE || "EST",
    port: PORT || 80,
    database: {
        pgDialect: "postgres",
        pgHost: PGHOST,
        pgPort: PGPORT || 5432,
        pgUsername: PGUSER,
        pgPassword: PGPASSWORD,
        pgDatabase: PGDATABASE,
    },
    defaultApiKey: DEFAULT_API_KEY,
    passwordSaltKey: PASSWORD_SALT_KEY || "",
    appUrl: APP_URL || "",
    sendGridAPIKey: SENDGRID_API_KEY || "",
    aws: {
        region: AWS_REGION,
        accessKeyId: AWS_KEY_ID,
        secretAccessKey: AWS_SECRET_KEY_ACCESS,
        bucketName: AWS_BUCKET || "",
    },
    defaultAdminEmail: DEFAULT_ADMIN_EMAIL || "prgowdham@gmail.com",
    emailImageBaseUrl: EMAIL_IMAGE_BASE_URL || "",
    fromEmail: FROM_EMAIL || "prgowdham@gmail.com",
    fromEmailDisplayName: FROM_EMAIL_DISPLAY_NAME || "Vtronics Automation",
    googleClientId: GOOGLE_CLIENT_ID || "",
    encryptionKey: ENCRYPTION_KEY || "",
};
